# Generated by Django 3.1 on 2020-08-24 08:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('grid', '0003_gridelement_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gridelement',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
